---
title: Get Started with Linux, on Windows!
contents:
  - title: Intro
    href: intro
  - title: Notepad++
    href: notepad
  - title: VirtualBox
    href: virtualbox
  - title: Vagrant
    href: vagrant
  - title: Cygwin
    href: cygwin
    children:
      - title: Cygwin Intro
        href: cygwin-intro
      - title: Road Map
        href: cygwin-road-map
      - title: Install Cygwin
        href: cygwin-install
      - title: Launch Cygwin Terminal
        href: cygwin-launch
      - title: Customize Terminal Appearance
        href: cygwin-terminal
      - title: Cygwin Directory Structure
        href: cygwin-directories
  - title: Virtual Machine Setup
    href: vm-setup
...
